name: goreleaser

on:
    workflow_dispatch:

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        outputs:
            output: ${{ steps.step1.outputs.version }}
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -
                name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.15.2
            -
                name: Install GoReleaser
                uses: goreleaser/goreleaser-action@v2
                with:
                    install-only: true
            - name: release dry run
              run: make release-dry-run
            - name: setup release environment
#              run: |-
#                   echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env
              run: |-
                   echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
            -
                name: Publish to github
                run: make release
#                env:
#                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
